name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Install Android SDK components
#        if: steps.android-cache.outputs.cache-hit != 'true'
      run: |
        sdkmanager "platform-tools" "platforms;android-36"
        sdkmanager "build-tools;36.0.0"
        sdkmanager "platforms;android-36.1"
        sdkmanager "ndk;29.0.14206865"
        sdkmanager "cmake;3.22.1"

    - name: Set up environment variables
      run: |
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/29.0.14206865" >> $GITHUB_ENV

    - name: Make scripts executable
      run: |
        chmod +x .ci/android/setup_environment.sh
        chmod +x .ci/android/build_app.sh

    - name: Setup environment
      run: ./.ci/android/setup_environment.sh

    - name: setup Android signing
      env:
        ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        ANDROID_KEY_BASE64: ${{ secrets.ANDROID_KEY_BASE64 }}
      run: |
        cp src-tauri/sign.patch/build.gradle.kts src-tauri/gen/android/app
        cd src-tauri/gen/android
        echo "keyAlias=$ANDROID_KEY_ALIAS" > keystore.properties
        echo "password=$ANDROID_KEY_PASSWORD" >> keystore.properties
        base64 -d <<< "$ANDROID_KEY_BASE64" > $RUNNER_TEMP/keystore.jks
        echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties

    - name: Build application
      env:
            RANLIB: ${{ env.ANDROID_NDK_ROOT }}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
            RANLIB_AARCH64_LINUX_ANDROID: ${{ env.ANDROID_NDK_ROOT }}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
            RANLIB_ARMV7_LINUX_ANDROIDEABI: ${{ env.ANDROID_NDK_ROOT }}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
            RANLIB_I686_LINUX_ANDROID: ${{ env.ANDROID_NDK_ROOT }}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
            RANLIB_X86_64_LINUX_ANDROID: ${{ env.ANDROID_NDK_ROOT }}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
            CARGO_TARGET_AARCH64_LINUX_ANDROID_RUSTFLAGS: "-C link-arg=-lc++_shared"
            CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_RUSTFLAGS: "-C link-arg=-lc++_shared"
            CARGO_TARGET_I686_LINUX_ANDROID_RUSTFLAGS: "-C link-arg=-lc++_shared"
            CARGO_TARGET_X86_64_LINUX_ANDROID_RUSTFLAGS: "-C link-arg=-lc++_shared"
      run: ./.ci/android/build_app.sh

    - name: Upload APKs
      uses: actions/upload-artifact@v4
      with:
        name: apks
        path: src-tauri/gen/android/app/build/outputs/apk/**/*.apk

    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: aab
        path: src-tauri/gen/android/app/build/outputs/bundle/**/*.aab

    - name: Deploy to Google Play
      if: startsWith(github.ref, 'refs/tags/v')
      run: ./.ci/android/deploy_google_play.sh
      env:
        GOOGLE_PLAY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}